添加字体
FloatTech/zbpdata pull request #2
Opened 2022-01-01 13:34 UTC by guohuiyuan

2022-01-01 14:53 UTC, fumiama commented
这是用在哪里的，不以大写开头的话是不会计算md5的，没法用GetLazyData

2022-01-01 14:53 UTC, fumiama requested changes
建议改一下文件夹首字母大写

2022-01-01 15:59 UTC, guohuiyuan commented
> 这是用在哪里的，不以大写开头的话是不会计算md5的，没法用GetLazyData

文字转图片字体

2022-01-02 05:47 UTC, fumiama commented
> > 这是用在哪里的，不以大写开头的话是不会计算md5的，没法用GetLazyData
> 
> 文字转图片字体

目前emoji没法渲染，你看要不要换个字体

2022-01-02 05:48 UTC, fumiama approved these changes

2022-01-02 13:27 UTC, merged